name: solid_color_fills
description: A Wallpaper that lets you set any solid color as wallpaper.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  convex_bottom_bar: ^2.6.0
  fluentui_system_icons: ^1.1.89
  flutter_animator: ^2.1.0
  flutter_colorpicker: ^0.3.4
  flutter_material_color_picker: ^1.0.5
  flutter_riverpod: ^0.13.1
  flutter_statusbarcolor: ^0.2.3
  introduction_screen: ^1.0.9
  modal_bottom_sheet: ^1.0.0+1
  open_file: ^3.0.3
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  system_properties: ^0.0.1
  theme_provider: ^0.4.0+1
  transparent_image: ^1.0.0
  url_launcher: ^5.7.10
  wallpaper_manager: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_rename_app: ^1.0.0

flutter_rename_app:
  application_name: Solid Color Fills
  dart_package_name: solid_color_fills
  application_id: com.makeshtech.solid_color_fills
  bundle_id: com.makeshtech.solid_color_fills

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
