name: solid_color_fills
description: A Wallpaper that lets you set any solid color as wallpaper.
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^2.2.0
  animations: ^2.0.0
  convex_bottom_bar: ^3.0.0
  fluentui_system_icons: ^1.1.126
  flutter_animator: ^3.1.1
  flutter_colorpicker: ^0.4.0
  flutter_riverpod: ^0.14.0+3
  flutter_wallpaper_manager: ^0.0.3
  introduction_screen: ^2.1.0
  material_color_picker_wns: ^1.0.8
  modal_bottom_sheet: ^2.0.0
  open_file: ^3.2.1
  page_transition: ^2.0.2
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  system_properties: ^0.0.1
  transparent_image: ^2.0.0
  url_launcher: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
